[tool.poetry]
authors = ["Shane Anderson <shane@reactivate.cx>"]
description = "Simple & fast multi-threaded S3 download tool."
keywords = ["aws", "s3"]
license = "MIT"
name = "s3fetch"
readme = "README.md"
repository = "https://github.com/rxvt/s3fetch"
version = "2.0.0"

[tool.poetry.dependencies]
boto3 = "^1.26.63"
click = "^8.0.0"
python = "^3.9"
urllib3 = "^1.26.8"
botocore-stubs = "^1.24.3"
boto3-stubs = {extras = ["s3"], version = "^1.26.68"}

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
nox = "^2022.11.21"
nox-poetry = "^1.0.3"
pytest = "^7.2"
pytest-cov = "^4.0.0"
pytest-mock = "^3.3.1"
mypy = "^0.931"
moto = {extras = ["s3"], version = "^4.1.3"}
coverage = {extras = ["toml"], version = "^6.4.1"}
types-setuptools = "^57.4.18"
safety = "^2.1.1"
ruff = "^0.1.15"
pre-commit = "^3.3.3"

[tool.poetry.scripts]
s3fetch = 's3fetch.cli:cli'

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.3.0"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["s3fetch"]

[tool.coverage.report]
show_missing = true
# fail_under = 100

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
files = "src/s3fetch, tests"

[[tool.mypy.overrides]]
module = ["s3fetch", "pkg_resources"]
ignore_missing_imports = true

[tool.ruff]
select = [
    # ANN Enable flake8-annotations warnings
    # B, B9 Enable flake8-bugbear. B9 is required for Bugbear’s more opinionated warnings.
    # C Enable mccabe warnings
    # D Enable flake8-docstring (pydocstyle) warnings
    # E, W Enable pycodestyle warnings
    # F Enable pyflakes warnings
    # I Enable flake8-isort warnings
    # S Enable flake8-bandit warnings
    "ANN",
    "B",
    "B9",
    "C",
    "D",
    "E",
    "W",
    "F",
    "I",
    "S"
]
target-version = "py39"
ignore = [
    "ANN204", # Ignore return type annotation for special methods
    "ANN101", #Ignore missing type annotation for self in method
    ]

[tool.ruff.pydocstyle]
# Use Google-style docstrings.
convention = "google"

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[tool.ruff.per-file-ignores]
"__init__.py" = ["D104"]
"tests/unit/test_s3fetch_old.py" = ["ALL"]  # Remove after all tests migrated
"tests/*" = [
    "ANN201",  # Ignore missing return types for test functions
    "ANN001",  # Ignore missing type annotations for test functions
    "D103",  # Ignore missing docstrings in test functions as the function name should be descriptive.
    "D100",
    "S101"  # Ignore use of 'assert'
    ]
"src/s3fetch/command.py" = ["ALL"]  # TODO: Remove after refactor is finished.

[tool.isort]
profile = "black"
