name: Test
on:
  - push
  - pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10"]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Poetry Install
        run: poetry install
      - name: Run Tests
        # pip resolver behaviour has changed, breaking nox testing
        # https://github.com/cjolowicz/nox-poetry/issues/196
        # run: poetry run nox --sessions tests-${{ matrix.python }}
        run: poetry run pytest tests/
