name: Test
on:
  - push
  - pull_request
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Poetry Install
        run: poetry install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935355401814:role/s3fetch-e2e-test-bot
          aws-region: us-east-2
      - name: Run Unit Tests
        run: poetry run nox --sessions unit-${{ matrix.python }}
      - name: Run Integration Tests
        run: poetry run nox --sessions integration-${{ matrix.python }}
      - name: Run E2E Tests
        run: poetry run nox --sessions e2e-${{ matrix.python }}
